"""Validation report formatters."""

import json
from datetime import datetime
from pathlib import Path
from typing import Protocol


class Reporter(Protocol):
    """Protocol for validation reporters."""

    def generate_report(self, conforms: bool, results_text: str, output_path: Path) -> None:
        """Generate validation report."""
        ...


class JSONReporter:
    """JSON format reporter."""

    def generate_report(self, conforms: bool, results_text: str, output_path: Path) -> None:
        """
        Generate JSON validation report.

        Args:
            conforms: Whether validation passed
            results_text: Validation results text
            output_path: Path to output file
        """
        report = {
            "timestamp": datetime.utcnow().isoformat(),
            "conforms": conforms,
            "status": "PASS" if conforms else "FAIL",
            "results": results_text,
        }

        with open(output_path, "w") as f:
            json.dump(report, f, indent=2)


class HTMLReporter:
    """HTML format reporter."""

    def generate_report(self, conforms: bool, results_text: str, output_path: Path) -> None:
        """
        Generate HTML validation report.

        Args:
            conforms: Whether validation passed
            results_text: Validation results text
            output_path: Path to output file
        """
        status_color = "green" if conforms else "red"
        status_text = "PASSED" if conforms else "FAILED"

        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>NKLLON Validation Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 8px 8px 0 0;
        }}
        .header h1 {{
            margin: 0 0 10px 0;
            font-size: 28px;
        }}
        .status {{
            color: {status_color};
            font-size: 24px;
            font-weight: bold;
            margin: 10px 0;
        }}
        .timestamp {{
            opacity: 0.9;
            font-size: 14px;
        }}
        .content {{
            padding: 30px;
        }}
        .results {{
            background: #f8f9fa;
            border-left: 4px solid #667eea;
            padding: 20px;
            margin-top: 20px;
            white-space: pre-wrap;
            font-family: 'Courier New', monospace;
            font-size: 14px;
            overflow-x: auto;
        }}
        .rules {{
            margin-top: 20px;
        }}
        .rule {{
            padding: 10px;
            margin: 10px 0;
            background: #e8f5e9;
            border-left: 4px solid #4caf50;
            border-radius: 4px;
        }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔍 NKLLON Hardware Topology Validation</h1>
            <p class="status">Status: {status_text}</p>
            <p class="timestamp">Generated: {
            datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        }</p>
        </div>
        <div class="content">
            <h2>Validation Results</h2>
            {
            (
                "<div class='rules'><h3>✅ All Constraints Satisfied:</h3>"
                "<div class='rule'>✓ Rule 1: eARC return path (SmartDisplay to PreAmp)</div>"
                "<div class='rule'>✓ Rule 2: Audio interfaces bypass KVMs (can connect to "
                "PreAmp)</div>"
                "<div class='rule'>✓ Rule 3: Bidirectional cables (USB-C to DisplayPort)</div>"
                "<div class='rule'>✓ Rule 4: Production uptime-critical ports</div></div>"
            )
            if conforms
            else ""
        }
            <div class="results">
                <h3>Detailed Report:</h3>
                {results_text if results_text else "No violations found."}
            </div>
        </div>
        <div class="footer">
            Generated by NKLLON Hardware Topology Validation System
        </div>
    </div>
</body>
</html>"""

        with open(output_path, "w") as f:
            f.write(html)


class MarkdownReporter:
    """Markdown format reporter."""

    def generate_report(self, conforms: bool, results_text: str, output_path: Path) -> None:
        """
        Generate Markdown validation report.

        Args:
            conforms: Whether validation passed
            results_text: Validation results text
            output_path: Path to output file
        """
        status_emoji = "✅" if conforms else "❌"
        status_text = "PASSED" if conforms else "FAILED"

        markdown = f"""# NKLLON Hardware Topology Validation Report

**Status**: {status_emoji} {status_text}
**Timestamp**: {datetime.utcnow().isoformat()}

---

## Validation Results

"""

        if conforms:
            markdown += """### ✅ All Constraints Satisfied

- ✓ **Rule 1**: eARC return path (SmartDisplay to PreAmp)
- ✓ **Rule 2**: Audio interfaces bypass KVMs (can connect to PreAmp)
- ✓ **Rule 3**: Bidirectional cables (USB-C to DisplayPort)
- ✓ **Rule 4**: Production uptime-critical ports

"""

        markdown += f"""### Detailed Report

```
{results_text if results_text else "No violations found."}
```

---

*Generated by NKLLON Hardware Topology Validation System*
"""

        with open(output_path, "w") as f:
            f.write(markdown)


def export_report(
    conforms: bool,
    results_text: str,
    output_path: Path,
    format: str = "json",
) -> None:
    """
    Export validation report in specified format.

    Args:
        conforms: Whether validation passed
        results_text: Validation results text
        output_path: Path to output file
        format: Report format (json, html, markdown)

    Raises:
        ValueError: If format is not supported
    """
    reporters: dict[str, Reporter] = {
        "json": JSONReporter(),
        "html": HTMLReporter(),
        "markdown": MarkdownReporter(),
        "md": MarkdownReporter(),
    }

    reporter = reporters.get(format.lower())
    if reporter is None:
        raise ValueError(
            f"Unsupported format: {format}. Supported formats: {', '.join(reporters.keys())}"
        )

    reporter.generate_report(conforms, results_text, output_path)
